version: "3.3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'test_db'
      MYSQL_USER: 'test_user'
      MYSQL_PASSWORD: 'test_password'
      MYSQL_ROOT_PASSWORD: 'test_password'
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql

  app:
    build: .
    container_name: sanic-test-app
    networks:
      - default
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql-db:
